project:
  type: website
  render:
    - "*.qmd"
    - "!publications/_template/"
    - "!people/_template/"


website:
  title: "Seafood Globalization Lab"
  site-url: "https://seafood-globalization-lab.github.io/lab-website/"
  repo-url: "https://github.com/Seafood-Globalization-Lab/lab-website"
  twitter-card: true
  #back-to-top-navigation: true
  page-navigation: false
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: © 2026  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/Seafood-Globalization-Lab/lab-website
  
  navbar:
    search: true
    title: false
    logo: /images/Seafood Globalization Lab_Logo_Full color_Horizontal.png
    background: "#F6F5F3"
    logo-alt: "Seafood Globalization Lab"
    left:
      - href: people/index.qmd
        text: people
      - href: publications/index.qmd
      - href: teaching/index.qmd
        text: Teaching
      - href: prospective-students/index.qmd
        text: Prospective Students
      - href: contact.qmd
        text: Contact


format:
  html:
    theme: 
      - styles/custom.scss
      - yeti
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images



